name: Tag Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: Tag Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Docker Build
        shell: bash
        run: docker build -t tiffdss:${{ github.sha }} .

      - name: Docker Run
        shell: bash
        run: docker run -v ${{ github.workspace }}:/tiffdss/ tiffdss:${{ github.sha }}

      - name: Zip Archive
        shell: bash
        run: zip -r tiffdss.zip --junk-paths ${{ github.workspace }}/src/output/

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/src/output/tiffdss.zip"
          bodyFile: ${{ github.workspace }}/RELEASE.md
          makeLatest: true
