name: Tag Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      
      # - name: Checkout HEC-DSS
      #   uses: actions/checkout@v3.3.0
      #   with: 
      #     repository: HydrologicEngineeringCenter/hec-dss@latest

      # - name: Build Library
      #   shell: bash
      #   run: |
      #     cd ${{ github.workspace }}/src
      #     make

      - name: Docker Build
        shell: bash
        run: docker build -t tiffdss:${{ github.sha }} .

      - name: Docker Run
        shell: bash
        run: docker run -v ${{ github.workspace }}/src/output:/tiffdss/src/output tiffdss:${{ github.sha }}

      - name: Tar Archive
        shell: bash
        run: |
          cd ${{ github.workspace }}/src/output
          tar -czf ${{ github.workspace }}/src/tiffdss_${{ github.ref_name }}.tar.gz ./tiffdss*

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "${{ github.workspace }}/src/tiffdss_${{ matrix.os }}_${{ github.ref_name }}*"
          bodyFile: ${{ github.workspace }}/RELEASE.md
          makeLatest: true
